env: "gymma"

env_args:
  key: robotarium_gym:MaterialTransport-v0
  time_limit: 1000
  seed: 2
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 4_000_000
